export const CHANGE_TABLE_BG_LECTURE = "CHANGE_TABLE_BG_LECTURE"
export const CHANGE_TABLE_BG_PRACTICE = "CHANGE_TABLE_BG_PRACTICE"
export const CHANGE_TABLE_FONT_COLOR_LECTURE = "CHANGE_TABLE_FONT_COLOR_LECTURE"
export const CHANGE_TABLE_FONT_COLOR_PRACTICE =
  "CHANGE_TABLE_FONT_COLOR_PRACTICE"
export const RESET_TABLE_STYLES = "RESET_TABLE_STYLES"
export const GET_TABLE_STYLES_FROM_LS = "GET_TABLE_STYLES_FROM_LS"
