export const CHANGE_BG_LECTURE = "CHANGE_BG_LECTURE"
export const CHANGE_BG_PRACTICE = "CHANGE_BG_PRACTICE"
export const CHANGE_FONT_COLOR_LECTURE = "CHANGE_FONT_COLOR_LECTURE"
export const CHANGE_FONT_COLOR_PRACTICE = "CHANGE_FONT_COLOR_PRACTICE"
